# coding: utf-8

"""
    Typed PID Maker - RESTful API

    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.

    The version of the OpenAPI document: 2.0.0
    Contact: support@datamanager.kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pytypid_generated_client.models.find_all200_response import FindAll200Response

class TestFindAll200Response(unittest.TestCase):
    """FindAll200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindAll200Response:
        """Test FindAll200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindAll200Response`
        """
        model = FindAll200Response()
        if include_optional:
            return FindAll200Response(
                data = [
                    null
                    ],
                last_page = 56
            )
        else:
            return FindAll200Response(
        )
        """

    def testFindAll200Response(self):
        """Test FindAll200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
