# coding: utf-8

"""
    Typed PID Maker - RESTful API

    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.

    The version of the OpenAPI document: 2.0.0
    Contact: support@datamanager.kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pytypid_generated_client.api.pid_management_api import PIDManagementApi


class TestPIDManagementApi(unittest.TestCase):
    """PIDManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PIDManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_pid(self) -> None:
        """Test case for create_pid

        Create a new PID record
        """
        pass

    def test_create_pids(self) -> None:
        """Test case for create_pids

        Create a multiple, possibly related PID records
        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        Returns all known PIDs. Supports paging, filtering criteria, and different formats.
        """
        pass

    def test_find_by_pid(self) -> None:
        """Test case for find_by_pid

        Returns a PID and its timestamps from the local store, if available.
        """
        pass

    def test_get_record(self) -> None:
        """Test case for get_record

        Get the record of the given PID.
        """
        pass

    def test_update_pid(self) -> None:
        """Test case for update_pid

        Update an existing PID record
        """
        pass


if __name__ == '__main__':
    unittest.main()
