# coding: utf-8

"""
    Typed PID Maker - RESTful API

    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.

    The version of the OpenAPI document: 2.0.0
    Contact: support@datamanager.kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pytypid_generated_client.api.actuator_api import ActuatorApi


class TestActuatorApi(unittest.TestCase):
    """ActuatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActuatorApi()

    def tearDown(self) -> None:
        pass

    def test_health(self) -> None:
        """Test case for health

        Actuator web endpoint 'health'
        """
        pass

    def test_info(self) -> None:
        """Test case for info

        Actuator web endpoint 'info'
        """
        pass

    def test_links(self) -> None:
        """Test case for links

        Actuator root web endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
