# coding: utf-8

"""
    Typed PID Maker - RESTful API

    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.

    The version of the OpenAPI document: 2.0.0
    Contact: support@datamanager.kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.pid_management_api import PIDManagementApi
from openapi_client.highlevel import SimpleRecord


class TestPIDManagementApi(unittest.TestCase):
    """PIDManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PIDManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_pid(self) -> None:
        """Test case for create_pid

        Create a new PID record
        """
        input = SimpleRecord.from_dict({
            "record": [
                { "key": "21.T11148/c692273deb2772da307f", "value": "1.0.0" }
            ]
        })

        assert input is not None, "Input should not be None"

        result = self.api.create_pid(
            pid_record=input.to_record()
        )

        print("Created:", result.to_json())
        assert result is not None, "Result should not be None"
        assert result.pid is not None, "PID should be set in the result"
        assert "21.T11148/c692273deb2772da307f" in result.to_str()

    def test_create_pids(self) -> None:
        """Test case for create_pids

        Create a multiple, possibly related PID records
        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        Returns all known PIDs. Supports paging, filtering criteria, and different formats.
        """
        pass

    def test_find_by_pid(self) -> None:
        """Test case for find_by_pid

        Returns a PID and its timestamps from the local store, if available.
        """
        pass

    def test_get_record(self) -> None:
        """Test case for get_record

        Get the record of the given PID.
        """
        pass

    def test_update_pid(self) -> None:
        """Test case for update_pid

        Update an existing PID record
        """
        pass


if __name__ == '__main__':
    unittest.main()
