# coding: utf-8

"""
    Typed PID Maker - RESTful API

    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.

    The version of the OpenAPI document: 2.0.0
    Contact: support@datamanager.kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "pytypid-generated-client"
VERSION = "0.2.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Typed PID Maker - RESTful API",
    author="KIT Data Manager Support",
    author_email="support@datamanager.kit.edu",
    url="https://github.com/kit-data-manager/typid-client",
    keywords=["OpenAPI", "OpenAPI-Generator", "Typed PID Maker - RESTful API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.
    """,  # noqa: E501
    package_data={"pytypid_generated_client": ["py.typed"]},
)