# coding: utf-8

# flake8: noqa
"""
    Typed PID Maker - RESTful API

    The Typed PID Maker is a service for creating, updating, obtaining and validating PID record information using Kernel Information Profiles, as defined by the Research Data Alliance.

    The version of the OpenAPI document: 2.0.0
    Contact: support@datamanager.kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.batch_record_response import BatchRecordResponse
from openapi_client.models.find_all200_response import FindAll200Response
from openapi_client.models.known_pid import KnownPid
from openapi_client.models.link import Link
from openapi_client.models.pid_record import PIDRecord
from openapi_client.models.pid_record_entry import PIDRecordEntry
from openapi_client.models.simple_pair import SimplePair
from openapi_client.models.simple_pid_record import SimplePidRecord
from openapi_client.models.tabulator_pagination_format import TabulatorPaginationFormat
from openapi_client.models.tabulator_pagination_format_known_pid import TabulatorPaginationFormatKnownPid
